### ISSUE TITLE
homebrew deprecations

### ISSUE THREAD

**Issue by arronmabrey** [choppsv1/homebrew-term24#10]
Looks like homebrew deprecated `sha1` in favor of `sh256`

```
Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/choppsv1/homebrew-term24/emacs-mac.rb:27:in `block in <class:EmacsMac>'
Please report this to the choppsv1/term24 tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/choppsv1/homebrew-term24/emacs-mac.rb:27:in `block in <class:EmacsMac>'
Please report this to the choppsv1/term24 tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/choppsv1/homebrew-term24/emacs-mac.rb:27:in `block in <class:EmacsMac>'
Please report this to the choppsv1/term24 tap!
```

**Comment by felixbuenemann** [comment]
The following should work:

``` ruby
    sha256 "9c3be8253c38357353c700903e8f77c71fad8f9bdcc3b843026d6cda23a858ae"
```

**Comment by jasonm23** [comment]
Pull request added https://github.com/choppsv1/homebrew-term24/pull/11
